### ISSUE TITLE
create_summary_report doesn't support more than 5 populations or models to compare

### ISSUE THREAD

**Issue by filbert42** [uriahf/rtichoke#70]
When I'm trying to compare more than 5 populations or models with create_summary_report it throws me an error:

`  <simpleError in data.frame(value = lvls_str, label = labels_values, stringsAsFactors = FALSE): arguments imply differing number of rows: 6, 10>`.
 
Is it a bug or is it an intended behavior? :)
![image](https://user-images.githubusercontent.com/21141202/180168187-8bee2aea-0890-47a9-a2c1-1079b63c726e.png)

**Comment by uriahf** [comment]
@filbert42 Are you familiar with a good reproducible example that is relevant?

I'll try to use [fairness::compas dataset](https://kozodoi.me/r/fairness/packages/2020/05/01/fairness-tutorial.html#ROC-AUC-parity) but it might be more intuitive to have examples of ROC with >5 subpopulations rather than specific metric in a table.

**Comment by uriahf** [comment]
- [ ] Support filtering for more than 5 populations when calling `render_performance_table()`
- [ ] Provide colors for more than 5 populations when calling `render_performance_table()`
- [ ] Provide colors for more than 5 populations when calling `plot_*_curve()`

**Comment by uriahf** [comment]
Should be fine now:

https://github.com/uriahf/rtichoke/commit/4756e3d273ae10af522026b64f0a533160cf14b1
https://github.com/uriahf/rtichoke/commit/b3ba132bdb4986f60ca98ac2b6e422c7d3d6ac1a


Reproducible Example:

```
library(purrr)
library(fairness)
library(dplyr)
library(rtichoke)

#collapse-show
# extract data

compas <- fairness::compas
df     <- compas[, !(colnames(compas) %in% c('probability', 'predicted'))]

# partitioning params
set.seed(77)
val_percent <- 0.3
val_idx     <- sample(1:nrow(df))[1:round(nrow(df) * val_percent)]

# partition the data
df_train <- df[-val_idx, ]
df_valid <- df[ val_idx, ]

# fit logit models
model1 <- glm(Two_yr_Recidivism ~ .,            
              data   = df_train, 
              family = binomial(link = 'logit'))

df_valid$prob_1 <- predict(model1, df_valid, type = 'response')
df_valid$Two_yr_Recidivism_01 <- ifelse(df_valid$Two_yr_Recidivism == 'yes', 1, 0)

named_group_split <- function(.tbl, ...) {
  grouped <- group_by(.tbl, ...)
  names <- rlang::inject(paste(!!!group_keys(grouped), sep = " / "))
  
  grouped %>% 
    group_split(.keep = FALSE) %>% 
    rlang::set_names(names)
}

df_valid_for_rtichoke <- df_valid %>%
  select(prob_1, Two_yr_Recidivism_01, ethnicity) %>% 
  list(
    probs = select(., ethnicity, prob_1) %>% 
      named_group_split(ethnicity) %>% 
      map(~ .x %>%
            pull(prob_1)),
    reals = select(., ethnicity, Two_yr_Recidivism_01) %>% 
      named_group_split(ethnicity)  %>% 
      map(~ .x %>%
            pull(Two_yr_Recidivism_01))
  )

create_summary_report(
  probs = df_valid_for_rtichoke$probs,
  reals = df_valid_for_rtichoke$reals
)
```
