### ISSUE TITLE
Calibration plot suggestion

### ISSUE THREAD

**Issue by urigott** [uriahf/rtichoke#91]
In calibration plot, add number of samples in hover box for each estimation point.

![image](https://user-images.githubusercontent.com/45831390/207259546-90f6cdca-421f-484e-90db-fa64575bd86c.png)

**Comment by uriahf** [comment]
Thanks for the suggestion!
The new hover text will look like that:

**Predicted:** 0.15
**Observed:** 0.24 (48 / 200)
